language: ruby
sudo: true
cache: bundler
rvm:
 - 2.2
 - 2.3.1
 - ruby-head

addons:
  apt:
    packages:
    - graphicsmagick
    - imagemagick

before_install:
 - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
