language: ruby
sudo: true
cache: bundler
rvm:
 - 2.2
 - 2.3.1
 - ruby-head
 - jruby-9.0.0.0.pre2

addons:
  apt:
    packages:
    - graphicsmagick
    - imagemagick

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq -y graphicsmagick imagemagick
 - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
